name: Linux Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: ubuntu:18.04

    steps:
    - uses: actions/checkout@v3
    
    - name: Add i386 architecture
      run: dpkg --add-architecture i386
      
    - name: Update repository
      run: apt-get update

    - name: Install build dependencies
      run: apt-get install -qq -y wget unzip build-essential gcc-4.8-multilib g++-4.8-multilib libgcc1:i386 libcurl4-openssl-dev:i386 zlib1g-dev:i386 libssl-dev:i386
    
    - name: Update alternatives
      run: update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

    - name: Run build
      working-directory: ./LogApi
      run: make
    
    - name: Move release file to publish
      run: |
        # Make Log API Path
        mkdir -p publish/addons/logapi/dlls

        # Move released file to dlls
        mv ./LogApi/Release/logapi_mm.so publish/addons/logapi/dlls

        # Copy cstrike contents to publish dir
        cp -ar cstrike/. publish

    - name: Deploy artifacts
      uses: actions/upload-artifact@v3
      with:
        name: logapi-linux
        path: publish/*
